import '../design/model.dart';

List<List<String>> countries = [
  ['Algeria', '+213', 'DZ'],
  ['Angola', '+244', 'AO'],
  ['Benin', '+229', 'BJ'],
  ['Botswana', '+267', 'BW'],
  ['Burkina Faso', '+226', 'BF'],
  ['Burundi', '+257', 'BI'],
  ['Cabo Verde', '+238', 'CV'],
  ['Cameroon', '+237', 'CM'],
  ['Central African Republic', '+236', 'CF'],
  ['Chad', '+235', 'TD'],
  ['Comoros', '+269', 'KM'],
  ['Congo (Brazzaville)', '+242', 'CG'],
  ['Congo (Kinshasa)', '+243', 'CD'],
  ['Djibouti', '+253', 'DJ'],
  ['Egypt', '+20', 'EG'],
  ['Equatorial Guinea', '+240', 'GQ'],
  ['Eritrea', '+291', 'ER'],
  ['Eswatini', '+268', 'SZ'],
  ['Ethiopia', '+251', 'ET'],
  ['Gabon', '+241', 'GA'],
  ['Gambia', '+220', 'GM'],
  ['Ghana', '+233', 'GH'],
  ['Guinea', '+224', 'GN'],
  ['Guinea-Bissau', '+245', 'GW'],
  ['Kenya', '+254', 'KE'],
  ['Lesotho', '+266', 'LS'],
  ['Liberia', '+231', 'LR'],
  ['Libya', '+218', 'LY'],
  ['Madagascar', '+261', 'MG'],
  ['Malawi', '+265', 'MW'],
  ['Mali', '+223', 'ML'],
  ['Mauritania', '+222', 'MR'],
  ['Mauritius', '+230', 'MU'],
  ['Morocco', '+212', 'MA'],
  ['Mozambique', '+258', 'MZ'],
  ['Namibia', '+264', 'NA'],
  ['Niger', '+227', 'NE'],
  ['Nigeria', '+234', 'NG'],
  ['Rwanda', '+250', 'RW'],
  ['Sao Tome and Principe', '+239', 'ST'],
  ['Senegal', '+221', 'SN'],
  ['Seychelles', '+248', 'SC'],
  ['Sierra Leone', '+232', 'SL'],
  ['Somalia', '+252', 'SO'],
  ['South Africa', '+27', 'ZA'],
  ['South Sudan', '+211', 'SS'],
  ['Sudan', '+249', 'SD'],
  ['Tanzania', '+255', 'TZ'],
  ['Togo', '+228', 'TG'],
  ['Tunisia', '+216', 'TN'],
  ['Uganda', '+256', 'UG'],
  ['Zambia', '+260', 'ZM'],
  ['Zimbabwe', '+263', 'ZW'],
];

// A global, constant list of all supported countries.
// By defining it here, any part of the app can import and use it.
final List<Country> allSupportedCountries =
    [
          ['Algeria', "+213", 'DZ'],
          ['Angola', '+244', 'AO'],
          ['Benin', '+229', 'BJ'],
          ['Botswana', '+267', 'BW'],
          ['Burkina Faso', '+226', 'BF'],
          ['Burundi', '+257', 'BI'],
          ['Cabo Verde', '+238', 'CV'],
          ['Cameroon', '+237', 'CM'],
          ['Central African Republic', '+236', 'CF'],
          ['Chad', '+235', 'TD'],
          ['Comoros', '+269', 'KM'],
          ['Congo (Brazzaville)', '+242', 'CG'],
          ['Congo (Kinshasa)', '+243', 'CD'],
          ['Djibouti', '+253', 'DJ'],
          ['Egypt', '+20', 'EG'],
          ['Equatorial Guinea', '+240', 'GQ'],
          ['Eritrea', '+291', 'ER'],
          ['Eswatini', '+268', 'SZ'],
          ['Ethiopia', '+251', 'ET'],
          ['Gabon', '+241', 'GA'],
          ['Gambia', '+220', 'GM'],
          ['Ghana', '+233', 'GH'],
          ['Guinea', '+224', 'GN'],
          ['Guinea-Bissau', '+245', 'GW'],
          ['Kenya', '+254', 'KE'],
          ['Lesotho', '+266', 'LS'],
          ['Liberia', '+231', 'LR'],
          ['Libya', '+218', 'LY'],
          ['Madagascar', '+261', 'MG'],
          ['Malawi', '+265', 'MW'],
          ['Mali', '+223', 'ML'],
          ['Mauritania', '+222', 'MR'],
          ['Mauritius', '+230', 'MU'],
          ['Morocco', '+212', 'MA'],
          ['Mozambique', '+258', 'MZ'],
          ['Namibia', '+264', 'NA'],
          ['Niger', '+227', 'NE'],
          ['Nigeria', '+234', 'NG'],
          ['Rwanda', '+250', 'RW'],
          ['Sao Tome and Principe', '+239', 'ST'],
          ['Senegal', '+221', 'SN'],
          ['Seychelles', '+248', 'SC'],
          ['Sierra Leone', '+232', 'SL'],
          ['Somalia', '+252', 'SO'],
          ['South Africa', '+27', 'ZA'],
          ['South Sudan', '+211', 'SS'],
          ['Sudan', '+249', 'SD'],
          ['Tanzania', '+255', 'TZ'],
          ['Togo', '+228', 'TG'],
          ['Tunisia', '+216', 'TN'],
          ['Uganda', '+256', 'UG'],
          ['Zambia', '+260', 'ZM'],
          ['Zimbabwe', '+263', 'ZW'],
        ]
        .map((list) => Country(name: list[0], code: list[1], isoCode: list[2]))
        .toList();
